// Home
export const SAVE_SCORE = 'SAVE_SCORE';
export const SAVE_QUESTION_NUMBER = 'SAVE_QUESTION_NUMBER';
export const GET_NEXT_QUESTION_DATA = 'GET_NEXT_QUESTION_DATA';
export const RESTART_GAME = 'RESTART_GAME';
